name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run lint
    - name: Run tape tests
      run: |
        xvfb-run --server-args="-screen 0 1920x1080x24" npm run ci:test:tape-run
